modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="energized"
version="1.0.0"
displayName="Energized"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mrahmalo.github.io/cubistic-games/"
authors="DracoFAAD029, Ahmalo,"

[[dependencies.energized]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




